Repository BrandwatchLtd/axiom-react, pull requests merged in 2018-06, with the labels that each got.

#572 feat(TableCell): Adds additional large verticalPadding option
  packages/axiom-components/src/Table/Table.css
  packages/axiom-components/src/Table/TableCell.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#574 fix(BarChart): Corrected where row visibility handler is added so fea…
  packages/axiom-charts/src/BarChart/BarChart.js
  packages/axiom-charts/src/ChartTable/ChartTableLabel.js
Labels: :+1: Code Review Passed

#575 fix(List): Fixes erroneous line-height by using flex
  packages/axiom-components/src/List/List.css
Labels: :+1: Code Review Passed

#579 fix(List): Tidies up the height of the vertical rule
  packages/axiom-components/src/List/List.css
Labels: :+1: Code Review Passed

#584 feat(Pictogram): Added new bar-percent-chart icon
  packages/axiom-components/src/Pictogram/Pictogram.js
  packages/axiom-components/src/Pictogram/svgs/bar-percent-chart.svg
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#588 fix(List): Reverts changes made in #575, #579 and #583.
  packages/axiom-components/src/List/List.css
Labels: :+1: Code Review Passed

#587 fix(UserMenu): Allow UserMenu positioning to be configurable
  packages/axiom-composites/src/UserMenu/UserMenu.js
Labels: :+1: Code Review Passed

#577 feat(Dropdown): Remove dropdown mask
  packages/axiom-components/src/AlertDropdown/AlertDropdown.js
  packages/axiom-components/src/Base/Base.css
  packages/axiom-components/src/Base/Base.js
  packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
  packages/axiom-components/src/Dropdown/Dropdown.js
  packages/axiom-components/src/Dropdown/DropdownContext.js
  packages/axiom-components/src/Position/Position.css
  packages/axiom-components/src/Position/Position.js
Labels: :woman_technologist: Code Review Needed

#593 fix(Tooltip): Delay prop warning
  packages/axiom-components/src/Tooltip/TooltipTarget.js
Labels: :+1: Code Review Passed

#594 fix(Dropdown): Restore pointer events
  packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
  packages/axiom-components/src/Dropdown/Dropdown.js
  packages/axiom-components/src/Dropdown/DropdownContext.js
  packages/axiom-components/src/Dropdown/DropdownTarget.js
Labels: :+1: Code Review Passed
