Repository BrandwatchLtd/axiom-react, pull requests merged in 2018-05, with the labels that each got.

#542 feat(TableRow): adds a hasBorder property to TableRow and TableCell
  packages/axiom-components/src/Table/Table.css
  packages/axiom-components/src/Table/TableRow.js
  packages/axiom-components/src/Table/TableRow.test.js
  packages/axiom-components/src/Table/__snapshots__/TableRow.test.js.snap
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#543 feat(Image): Add 'ratios' prop to allow image grid height to be confi…
  packages/axiom-components/src/Card/Card.css
  packages/axiom-components/src/Card/CardImages.js
  packages/axiom-components/src/Card/__snapshots__/CardImages.test.js.snap
Labels: :+1: Code Review Passed

#545 refactor(BarChartBars): Move label from Bar to upper component
  packages/axiom-charts/src/BarChart/BarChart.css
  packages/axiom-charts/src/BarChart/BarChartBars.js
Labels: :+1: Code Review Passed

#547 fix(Dropdown): Omit onRequestCloseDropdown from reaching DropdownContext
  packages/axiom-components/src/Dropdown/DropdownContext.js
Labels: :+1: Code Review Passed

#546 feat(Bar): Add new prop striped
  packages/axiom-charts/src/Bar/Bar.css
  packages/axiom-charts/src/Bar/Bar.js
  packages/axiom-charts/src/Bar/Bar.test.js
  packages/axiom-charts/src/Bar/__snapshots__/Bar.test.js.snap
  packages/axiom-charts/src/Bar/__snapshots__/Bars.test.js.snap
  packages/axiom-charts/src/BulletChart/__snapshots__/BulletBars.test.js.snap
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#550 fix(BarChart): Do not highlight all bars with same color if there is only one bar per row
  packages/axiom-charts/src/BarChart/BarChart.js
  packages/axiom-charts/src/BarChart/BarChartBars.js
Labels: :+1: Code Review Passed

#557 fix(Button): Active state being applied when clicking on svg element
  packages/axiom-components/src/Button/Button.css
Labels: :+1: Code Review Passed

#556 fix(Tab): Only add as a title if the title is a string
  packages/axiom-components/src/Tabset/Tab.js
  packages/axiom-components/src/Tabset/Tab.test.js
  packages/axiom-components/src/Tabset/__snapshots__/Tab.test.js.snap
Labels: :+1: Code Review Passed

#560 fix(BarChart): Fix hover when BarChart has just single values
  packages/axiom-charts/src/BarChart/BarChart.js
Labels: :+1: Code Review Passed

#562 fix(TextInput): Ensuring native input events are passed through correctly.
  packages/axiom-components/src/Form/TextInput.js
Labels: :+1: Code Review Passed

#561 fix(BarChart): vertically center label when size is specified
  packages/axiom-charts/src/BarChart/BarChart.css
Labels: :+1: Code Review Passed

#563 fix(Textarea): Focus border color
  packages/axiom-components/src/Form/TextArea.css
Labels: :+1: Code Review Passed

#559 feat(BarChart): Added rowsConcealable prop that activates show/hide controls for barchart rows
  packages/axiom-charts/src/BarChart/BarChart.js
  packages/axiom-charts/src/BarChart/BarChartBars.js
  packages/axiom-charts/src/BarChart/CombinedBar.test.js
  packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
  packages/axiom-charts/src/BarChart/utils.js
  packages/axiom-charts/src/ChartTable/ChartTableLabel.js
  packages/axiom-charts/src/ChartTable/ChartTableLabel.test.js
  packages/axiom-charts/src/ChartTable/__snapshots__/ChartTableLabel.test.js.snap
  site/components/Documentation/Resources/Charts/BarChart.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#568 refactor(CombinedBar): To accept tooltip and dropdown props
  packages/axiom-charts/src/BarChart/BarChartBars.js
  packages/axiom-charts/src/BarChart/CombinedBar.js
  packages/axiom-charts/src/BarChart/CombinedBar.test.js
  packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
Labels: :woman_technologist: Code Review Needed

#569 fix(TableCell): removes typo causing proptype warnings
  packages/axiom-components/src/Table/TableCell.js
Labels: :+1: Code Review Passed
