Repository BrandwatchLtd/axiom-react, pull requests merged in 2018-09, with the labels that each got.

#657 fix(Slider): Fix onSlideEnd being unrecognised
  packages/axiom-components/src/Slider/Slider.js
Labels: :+1: Code Review Passed

#659 fix(TextInput): Fix input growing to available space
  packages/axiom-components/src/Form/InputWrapper.css
  packages/axiom-components/src/Form/InputWrapper.js
Labels: :+1: Code Review Passed

#653 fix(Dropdown): Implement native style hover and focus
  packages/axiom-components/package.json
  packages/axiom-components/src/Context/Context.css
  packages/axiom-components/src/Dropdown/DropdownContext.js
  yarn.lock
Labels: :+1: Code Review Passed

#665 feat(Grid): Added direction property to control direction of grid
  packages/axiom-components/src/Grid/Grid.css
  packages/axiom-components/src/Grid/Grid.js
  packages/axiom-components/src/Grid/GridCell.js
Labels: :woman_technologist: 2nd Code Review Needed

#670 fix(SparkLine): When there is no difference in values
  packages/axiom-charts/src/SparkLine/SparkLine.js
  site/components/Documentation/Resources/Charts/SparkLine.js
  site/components/Documentation/Resources/Charts/chartData.js
Labels: :woman_technologist: 1st Code Review Needed

#671 feat(Colors): Update values of existing colors
  packages/axiom-materials/src/colors.css
  packages/axiom-materials/src/colors.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#672 fix(Table): Vertical cell padding and medium value missing
  packages/axiom-components/src/Table/Table.css
  packages/axiom-components/src/Table/TableCell.js
  packages/axiom-components/src/Table/__snapshots__/TableCell.test.js.snap
  packages/axiom-components/src/Table/__snapshots__/TableRow.test.js.snap
Labels: :woman_technologist: 1st Code Review Needed

#668 fix(TextInput): Add ability to focus TextInput in axiom.
  packages/axiom-components/src/Base/Base.js
  packages/axiom-components/src/Form/TextInput.js
Labels: :woman_technologist: 2nd Code Review Needed

#674 Upgrade Jest to 23.6.0
  package.json
  packages/axiom-charts/src/Bar/__snapshots__/Bar.test.js.snap
  packages/axiom-charts/src/Bar/__snapshots__/Bars.test.js.snap
  packages/axiom-charts/src/BarChart/__snapshots__/CombinedBar.test.js.snap
  packages/axiom-charts/src/BulletChart/__snapshots__/BulletBars.test.js.snap
  packages/axiom-charts/src/Chart/ChartBody.test.js
  packages/axiom-charts/src/Chart/__snapshots__/ChartBody.test.js.snap
  packages/axiom-charts/src/ChartTable/__snapshots__/ChartTableLabel.test.js.snap
  packages/axiom-charts/src/ChartTable/__snapshots__/ChartTableRows.test.js.snap
  packages/axiom-charts/src/DataPoint/__snapshots__/DataPoint.test.js.snap
  packages/axiom-charts/src/DataPoint/__snapshots__/DataPoints.test.js.snap
  packages/axiom-charts/src/WordCloud/__snapshots__/Word.test.js.snap
  packages/axiom-charts/src/WordCloud/__snapshots__/WordCloud.test.js.snap
  packages/axiom-components/src/AlertCard/__snapshots__/AlertCard.test.js.snap
  packages/axiom-components/src/Badge/Badge.test.js
  packages/axiom-components/src/Badge/__snapshots__/Badge.test.js.snap
  packages/axiom-components/src/Badge/__snapshots__/BadgeGroup.test.js.snap
  packages/axiom-components/src/Base/Base.test.js
  packages/axiom-components/src/Base/__snapshots__/Base.test.js.snap
  packages/axiom-components/src/Button/Button.test.js
  packages/axiom-components/src/Button/__snapshots__/Button.test.js.snap
  packages/axiom-components/src/Button/__snapshots__/ButtonGroup.test.js.snap
  packages/axiom-components/src/Context/__snapshots__/ContextMenu.test.js.snap
  packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
  packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
  packages/axiom-components/src/Dialog/__snapshots__/Dialog.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/CheckBox.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/CheckBoxGroup.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/RadioButton.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/RadioButtonGroup.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/TextArea.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/TextInput.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/TextInputButton.test.js.snap
  packages/axiom-components/src/Grid/Grid.test.js
  packages/axiom-components/src/Grid/GridCell.test.js
  packages/axiom-components/src/Grid/__snapshots__/Grid.test.js.snap
  packages/axiom-components/src/Grid/__snapshots__/GridCell.test.js.snap
  packages/axiom-components/src/Icon/__snapshots__/IconButton.test.js.snap
  packages/axiom-components/src/Label/Label.test.js
  packages/axiom-components/src/Menu/__snapshots__/Menu.test.js.snap
  packages/axiom-components/src/Menu/__snapshots__/MenuItem.test.js.snap
  packages/axiom-components/src/Modal/__snapshots__/Modal.test.js.snap
  packages/axiom-components/src/Pagination/__snapshots__/Pagination.test.js.snap
  packages/axiom-components/src/Pagination/__snapshots__/PaginationButton.test.js.snap
  packages/axiom-components/src/Progress/__snapshots__/ProgressButton.test.js.snap
  packages/axiom-components/src/Select/__snapshots__/Select.test.js.snap
  packages/axiom-components/src/Table/__snapshots__/TableBody.test.js.snap
  packages/axiom-components/src/Table/__snapshots__/TableHeader.test.js.snap
  packages/axiom-components/src/Table/__snapshots__/TableHeaderLabel.test.js.snap
  packages/axiom-components/src/Table/__snapshots__/TableRow.test.js.snap
  packages/axiom-components/src/Tabset/__snapshots__/Tab.test.js.snap
  packages/axiom-components/src/Tip/__snapshots__/Tip.test.js.snap
  packages/axiom-components/src/Toggle/__snapshots__/Toggle.test.js.snap
  yarn.lock
Labels: :woman_technologist: 2nd Code Review Needed
