Repository BrandwatchLtd/axiom-react, pull requests merged in 2018-03, with the labels that each got.

#469 chore(Site): Remove gzipping from images (its not a thing)
  scripts/publish_site.sh
  webpack.static.config.js
Labels: Code Review Passed

#474 chore(Build): Fixes package publishing
  .travis.yml
  github_deploy_key.enc
  package.json
  scripts/build_packages.sh
  scripts/ci_setup.sh
  scripts/publish_build.sh
  scripts/publish_packages.sh
  scripts/publish_site.sh
  scripts/start_development.sh
Labels: Code Review Passed

#476 fix(Dependecy): Added missing @brandwatch/axiom-automation-testing de…
  packages/axiom-components/package.json
Labels: Code Review Passed

#477 fix(TextGroup): Added missing TextGroup export under new name of Inpu…
  MIGRATION.md
  packages/axiom-components/src/Form/InputWrapper.css
  packages/axiom-components/src/Form/InputWrapper.js
  packages/axiom-components/src/Form/TextArea.js
  packages/axiom-components/src/Form/TextInput.js
  packages/axiom-components/src/Form/__snapshots__/TextArea.test.js.snap
  packages/axiom-components/src/Form/__snapshots__/TextInput.test.js.snap
  packages/axiom-components/src/Select/__snapshots__/Select.test.js.snap
  packages/axiom-components/src/index.js
Labels: :+1: Code Review Passed

#478 fix(Card): Added CardImage dotted separator
  packages/axiom-components/src/Card/Card.css
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#479 feat(Package): Added new babel-plugin-axiom-imports (modified version…
  .babelrc
  MIGRATION.md
  packages/axiom-materials/src/importCssVariables.js
  packages/axiom-materials/src/index.js
  packages/babel-plugin-axiom-imports/package.json
  packages/babel-plugin-axiom-imports/src/__snapshots__/babel-plugin-axiom-imports.test.js.snap
  packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.js
  packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.test.js
  packages/babel-plugin-axiom-imports/src/resolve-import.js
  packages/babel-plugin-axiom-imports/test/alias.js
  packages/babel-plugin-axiom-imports/test/destructure.js
  packages/babel-plugin-axiom-imports/test/scoped.js
Labels: :+1: Code Review Passed

#484 fix(ChedioButtox): adds disabled styling to Chedio labels
  packages/axiom-components/src/Form/ChedioButtox.css
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#485 feat: adds an axis utils
  packages/axiom-charts/src/index.js
  packages/axiom-charts/src/utils/__snapshots__/axisUtils.test.js.snap
  packages/axiom-charts/src/utils/axisUtils.js
  packages/axiom-charts/src/utils/axisUtils.test.js
Labels: :+1: Code Review Passed

#486 fix(DotPlot): Incorrectly faded Benchmarking and Difference lines
  packages/axiom-charts/src/DotPlotChart/utils.js
  packages/axiom-charts/src/DotPlotChart/utils.test.js
Labels: :+1: Code Review Passed

#489 fix(TableRow): Design fix for a dotted separator between table rows.
  packages/axiom-components/src/Table/Table.css
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#492 fix(stringToColor): Regression from product color update. stringToCol…
  packages/axiom-utils/src/stringToColor.js
  packages/axiom-utils/src/stringToColor.test.js
Labels: :+1: Code Review Passed

#493 fix(axisUtil.getAxisUpper) rounds to same order of magnitude instead
  packages/axiom-charts/src/utils/axisUtils.js
  packages/axiom-charts/src/utils/axisUtils.test.js
Labels: :+1: Code Review Passed

#494 fix(BarChart) do not break labels with (thin)spaces
  packages/axiom-charts/src/ChartTable/ChartTableRows.js
  packages/axiom-charts/src/ChartTable/__snapshots__/ChartTableRows.test.js.snap
Labels: :+1: Code Review Passed

#495 fix(Select): Only add onClear 'X' when an onClear is given
  packages/axiom-components/src/Select/Select.js
Labels: :+1: Code Review Passed

#496 fix(BarChart): hide other bars only when BarChart displays multiple bars
  packages/axiom-charts/src/BarChart/BarChart.js
  packages/axiom-charts/src/BarChart/utils.js
  packages/axiom-charts/src/BarChart/utils.test.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#498 fix(Tabset): Call onClick for Tabs when using controlled Tabset compo…
  packages/axiom-components/src/Tabset/Tabset.js
Labels: :+1: Code Review Passed

#497 Validate commit message to ensure correct format
  .travis.yml
  package.json
  scripts/validate_commit_messages.sh
Labels: :woman_technologist: Code Review Needed

#501 feat(Base): Add container property to Base component for relative positioning
  packages/axiom-components/src/Base/Base.css
  packages/axiom-components/src/Base/Base.js
  packages/axiom-components/src/Base/Base.test.js
  packages/axiom-components/src/Base/__snapshots__/Base.test.js.snap
Labels: :+1: Code Review Passed

#500 chore(CI): Detect modified yarn.lock on CI
  .travis.yml
  yarn.lock
Labels: :+1: Code Review Passed

#502 chore(tests): Always run tests in same timezone
  package.json
Labels: :+1: Code Review Passed
