Repository BrandwatchLtd/axiom-react, pull requests merged in 2018-07, with the labels that each got.

#600 docs(TooltipContext): add documented support for color prop
  packages/axiom-components/src/Tooltip/TooltipContext.js
  site/components/Documentation/Resources/Components/Tooltip.js
Labels: :+1: Code Review Passed

#601 fix(Position): Boundary element to be viewport
  packages/axiom-components/src/Position/Position.js
Labels: :+1: Code Review Passed

#595 feat(StatusBadge): Added new StatusBadge component
  packages/axiom-components/src/StatusBadge/StatusBadge.css
  packages/axiom-components/src/StatusBadge/StatusBadge.js
  packages/axiom-components/src/StatusBadge/svgs/alpha.svg
  packages/axiom-components/src/StatusBadge/svgs/beta.svg
  packages/axiom-components/src/StatusBadge/svgs/internal.svg
  packages/axiom-components/src/StatusBadge/svgs/new.svg
  packages/axiom-components/src/StatusBadge/svgs/prototype.svg
  packages/axiom-components/src/index.js
  site/components/Documentation/Resources/Components.js
  site/components/Documentation/Resources/Components/StatusBadge.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#602 feat (Dialog) : Added the ability to set width on the Dialog componen…
  packages/axiom-components/src/Dialog/Dialog.css
  packages/axiom-components/src/Dialog/Dialog.js
  packages/axiom-components/src/Dialog/Dialog.test.js
  packages/axiom-components/src/Dialog/__snapshots__/Dialog.test.js.snap
  site/components/Documentation/Resources/Components/Dialog.js
Labels: :+1: Code Review Passed

#604 SW-140 Close Modal when pressing Esc
  packages/axiom-components/src/AlertDialog/AlertDialog.js
  packages/axiom-components/src/Dialog/Dialog.js
  packages/axiom-components/src/Modal/Modal.js
  packages/axiom-components/src/Modal/Modal.test.js
  packages/axiom-components/src/Modal/__snapshots__/Modal.test.js.snap
Labels: :woman_technologist: 2nd Code Review Needed

#608 chore(CI): use git remote with ssh
  scripts/publish_packages.sh
Labels: :+1: Code Review Passed

#611 chore(Site): Reenable site publishing
  .travis.yml
  scripts/publish_site.sh
Labels: :+1: Code Review Passed

#610 fix(Typography): increase line heights for display and display2
  packages/axiom-materials/src/typography.css
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#606 feat(Dropdowns): Set show arrow to true in Dropdown and Position comp…
  packages/axiom-charts/src/ChartContext/ChartContext.js
  packages/axiom-components/src/ColorPicker/ColorPicker.js
  packages/axiom-components/src/DataPicker/DataPicker.js
  packages/axiom-components/src/DatePicker/DatePicker.js
  packages/axiom-components/src/Dropdown/Dropdown.js
  packages/axiom-components/src/Position/Position.js
  packages/axiom-components/src/Select/Select.js
  packages/axiom-components/src/Tooltip/Tooltip.js
  site/components/Documentation/Resources/Charts/WordCloud.js
  site/components/Documentation/Resources/Components/AlertDropdown.js
  site/components/Documentation/Resources/Components/Dialog.js
  site/components/Documentation/Resources/Components/Dropdown.js
  site/components/Documentation/Resources/Components/Position.js
Labels: :+1: Code Review Passed

#615 feat(Slider): Added slider component
  packages/axiom-components/src/Slider/Slider.css
  packages/axiom-components/src/Slider/Slider.js
  packages/axiom-components/src/index.js
  site/components/Documentation/Resources/Components.js
  site/components/Documentation/Resources/Components/Slider.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#617 chore(React16.4.1): Updates React@16.4.1 and React-dom@16.4.1
  package.json
  packages/axiom-charts/package.json
  packages/axiom-components/package.json
  packages/axiom-composites/package.json
  packages/axiom-utils/package.json
  yarn.lock
Labels: :woman_technologist: 2nd Code Review Needed

#623 feat(TabSet): Add variable spacing
  packages/axiom-components/src/Tabset/Tabset.js
Labels: :+1: Code Review Passed

#624 chore(npmAuthToken): Regenerated the NPM Auth token for publishing
  .travis.yml
Labels: :+1: Code Review Passed

#625 feat(Notification): adds atId for close button on Notification popup
  packages/axiom-automation-testing/ids.json
  packages/axiom-components/src/Notification/Notification.js
  packages/axiom-components/src/Notification/__snapshots__/Notification.test.js.snap
Labels: :+1: Code Review Passed

#627 feat(Icon): adds new Instagram icon
  packages/axiom-components/src/Icon/Icon.js
  packages/axiom-components/src/Icon/svgs/instagram.svg
Labels: :+1: Code Review Passed

#622 feat(ArrowHead): Add an ArrowHead component to axiom.
  packages/axiom-components/src/Context/Context.css
  packages/axiom-components/src/Context/Context.js
  packages/axiom-components/src/Context/__snapshots__/Context.test.js.snap
  packages/axiom-components/src/Tip/Tip.css
  packages/axiom-components/src/Tip/Tip.js
  packages/axiom-components/src/Tip/Tip.test.js
  packages/axiom-components/src/Tip/__snapshots__/Tip.test.js.snap
  packages/axiom-components/src/index.js
  site/components/Documentation/Resources/Components.js
  site/components/Documentation/Resources/Components/Tip.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#630 Remove default color from tip
  packages/axiom-components/src/Context/__snapshots__/Context.test.js.snap
  packages/axiom-components/src/Tip/Tip.js
  packages/axiom-components/src/Tip/__snapshots__/Tip.test.js.snap
  site/components/Documentation/Resources/Components/Tip.js
Labels: :woman_technologist: 2nd Code Review Needed

#631 fix(Tip): Properly position tip when position is top
  packages/axiom-components/src/Context/Context.css
  packages/axiom-components/src/Tip/Tip.css
Labels: :+1: Code Review Passed

#633 fix(BarChart): only fade other benchmark lines
  packages/axiom-charts/src/BarChart/BarChart.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed
