Repository BrandwatchLtd/axiom-react, pull requests merged in 2018-04, with the labels that each got.

#503 feat(Colours): Added social interaction colours
  packages/axiom-materials/src/colors.css
  packages/axiom-materials/src/colors.js
  site/components/Documentation/Resources/Materials/Colors.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#506 fix(axisUtils): when upper and lower are equal return no labels
  packages/axiom-charts/src/utils/axisUtils.js
  packages/axiom-charts/src/utils/axisUtils.test.js
Labels: :+1: Code Review Passed

#509 fix(Editable): Fixes issue where given prop is the same as it was before
  packages/axiom-components/src/Editable/EditableLine.js
Labels: :+1: Code Review Passed

#505 fix(Dropdown): Open dropdown when DropdownTarget has focus
  packages/axiom-components/src/DataPicker/__snapshots__/DataPicker.test.js.snap
  packages/axiom-components/src/Dropdown/Dropdown.js
  packages/axiom-components/src/Dropdown/DropdownSource.js
  packages/axiom-components/src/Dropdown/DropdownTarget.js
  site/components/Documentation/Resources/Components/Dropdown.js
Labels: :+1: Code Review Passed

#510 fix(Link): Apply hover states when Links are focused
  packages/axiom-components/src/Typography/Link.css
Labels: :+1: Code Review Passed, :art: Design Review Needed

#511 fix(Enzyme): Moves enzyme-to-json to a top level dev dependency
  package.json
  packages/axiom-components/package.json
Labels: :+1: Code Review Passed

#514 feat(charts): add support for social colors
  packages/axiom-charts/src/Bar/Bar.css
  packages/axiom-charts/src/Bar/Bar.js
  packages/axiom-charts/src/DataPoint/DataPoint.js
  packages/axiom-charts/src/DataPoint/DataPoints.css
  packages/axiom-charts/src/Line/Line.css
  packages/axiom-charts/src/Line/Line.js
  packages/axiom-charts/src/Line/LinePoint.js
Labels: :+1: Code Review Passed

#515 fix(BarChart): fix stale label when using duplicate labels
  packages/axiom-charts/src/BarChart/BarChart.js
Labels: :+1: Code Review Passed

#516 Pass index of data to tooltip callback of the linechart
  packages/axiom-charts/src/Line/LinePoint.js
  packages/axiom-charts/src/LineChart/LineChart.js
Labels: :+1: Code Review Passed

#519 fix(Badge): Adds interactive styling when onClick is given
  packages/axiom-components/src/Badge/Badge.css
  packages/axiom-components/src/Badge/Badge.js
  packages/axiom-components/src/Badge/Badge.test.js
  packages/axiom-components/src/Badge/__snapshots__/Badge.test.js.snap
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#520 feat(Console): Added further shading possibilities
  packages/axiom-components/src/Platform/Console.js
  packages/axiom-components/src/Platform/ConsoleHeader.js
  packages/axiom-components/src/Platform/Platform.css
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#513 fix(Candytar): Only the user defined product colour set are supported…
  packages/axiom-components/src/Avatar/Candytar.js
Labels: :+1: Code Review Passed

#521 fix(Badge): pass through onClick property
  packages/axiom-components/src/Badge/Badge.js
  packages/axiom-components/src/Badge/__snapshots__/Badge.test.js.snap
  packages/axiom-components/src/Badge/__snapshots__/BadgeGroup.test.js.snap
Labels: :+1: Code Review Passed

#525 feat(LineChart): Added onPointClick action to the LineChart
  packages/axiom-charts/src/Line/LinePoint.js
  packages/axiom-charts/src/LineChart/LineChart.js
  packages/axiom-components/src/Tooltip/TooltipTarget.js
Labels: :+1: Code Review Passed

#522 chore(Transition): Add new Transition component
  packages/axiom-components/package.json
  packages/axiom-components/src/Transition/Transition.css
  packages/axiom-components/src/Transition/Transition.js
  packages/axiom-components/src/Transition/Transition.test.js
  packages/axiom-components/src/Transition/__snapshots__/Transition.test.js.snap
  packages/axiom-components/src/index.js
  site/components/Documentation/Resources/Components.js
  site/components/Documentation/Resources/Components/Transition.js
  yarn.lock
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#526 fix(Select): Pass onRequest callbacks to Dropdown
  packages/axiom-components/src/Select/Select.js
Labels: :+1: Code Review Passed

#529 fix(Transition): Slide into correct direction on initial change
  packages/axiom-components/src/Transition/Transition.js
Labels: :+1: Code Review Passed

#531 feat(ContextMenuItem): Add icon prop to specify menu item icon
  packages/axiom-components/src/Context/ContextMenuItem.js
  packages/axiom-components/src/Context/ContextMenuItem.test.js
  packages/axiom-components/src/Context/__snapshots__/ContextMenuItem.test.js.snap
Labels: :+1: Code Review Passed

#528 More specific cache control directives
  scripts/publish_site.sh
Labels: :+1: Code Review Passed

#534 fix(Context): Scroll when using the menu or content components as scr…
  packages/axiom-components/src/Context/Context.css
Labels: :+1: Code Review Passed

#533 feat(Icon): Added new 'at', 'exlcude' and 'line-graph' icons and upda…
  packages/axiom-components/src/Icon/Icon.js
  packages/axiom-components/src/Icon/svgs/at.svg
  packages/axiom-components/src/Icon/svgs/exclude.svg
  packages/axiom-components/src/Icon/svgs/home.svg
  packages/axiom-components/src/Icon/svgs/line-graph.svg
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#535 Pass closeDropdown action from context down to DropdownSource component
  packages/axiom-components/src/Dropdown/DropdownSource.js
Labels: :+1: Code Review Passed

#532 feat(Dropdown): add support for submenus
  packages/axiom-components/src/Context/Context.css
  site/components/Documentation/Resources/Components/Dropdown.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#538 feat(CheckBox): Added indeterminate property
  packages/axiom-components/src/Form/CheckBox.js
  packages/axiom-components/src/Form/CheckBox.test.js
  packages/axiom-components/src/Form/ChedioButtox.css
  packages/axiom-components/src/Form/ChedioButtox.js
  packages/axiom-components/src/Form/__snapshots__/CheckBox.test.js.snap
Labels: :+1: Code Review Passed

#540 fix(ContextMenuItem): Pass down indeterminate property to checkbox
  packages/axiom-components/src/Context/ContextMenuItem.js
Labels: :woman_technologist: Code Review Needed

#541 feat(Card): Added CardImages component to support multiple images
  packages/axiom-components/src/Card/Card.css
  packages/axiom-components/src/Card/CardImages.js
  packages/axiom-components/src/Card/CardImages.test.js
  packages/axiom-components/src/Card/__snapshots__/CardImages.test.js.snap
  packages/axiom-components/src/index.js
  site/assets/card-1.jpeg
  site/assets/card-2.jpeg
  site/assets/card-3.jpeg
  site/assets/card-4.jpeg
  site/components/Documentation/Resources/Components/Card.js
Labels: :+1: Code Review Passed, :+1: Design Review Passed
