Repository BrandwatchLtd/axiom-react, pull requests merged in 2018-08, with the labels that each got.

#636 fix(Reveal): Add check for inner if component is removed before callb…
  packages/axiom-components/src/Reveal/Reveal.js
Labels: :+1: Code Review Passed

#637 fix(ColorPicker): cascades size property to main ColorPickerOption
  packages/axiom-components/src/ColorPicker/ColorPicker.js
  packages/axiom-components/src/ColorPicker/ColorPicker.test.js
  packages/axiom-components/src/ColorPicker/__snapshots__/ColorPicker.test.js.snap
Labels: :art: Design Review Needed

#632 fix(InputWrapper) Using 'node' prop-type for label prop in InputWrapper.
  packages/axiom-components/src/Form/InputWrapper.js
  packages/axiom-components/src/Form/TextArea.js
Labels: :+1: Code Review Passed

#638 chore(npmAuth): fix npm config call
  scripts/publish_packages.sh
Labels: :+1: Code Review Passed

#642 fix(Card): Fixes issue with image grids in Safari
  packages/axiom-components/src/Card/Card.css
Labels: :+1: Code Review Passed

#643 feat(Dialog): Configurable 'padding' prop
  packages/axiom-components/src/Dialog/Dialog.js
  packages/axiom-components/src/Dialog/__snapshots__/Dialog.test.js.snap
  packages/axiom-components/src/Modal/Modal.css
  packages/axiom-components/src/Modal/Modal.js
  packages/axiom-components/src/Modal/__snapshots__/Modal.test.js.snap
Labels: :+1: Code Review Passed, :+1: Design Review Passed

#646 fix(BarChart): fix CombinedBar data prop type
  packages/axiom-charts/src/BarChart/CombinedBar.js
Labels: :+1: Code Review Passed

#645 chore(Publishing): Use npm client for publishing with lerna
  scripts/publish_packages.sh
Labels: :+1: Code Review Passed

#628 chore(dates): replace date-fns with luxon
  packages/axiom-components/package.json
  packages/axiom-components/src/DatePicker/utils.js
  packages/axiom-formatting/package.json
  packages/axiom-formatting/src/filenameDate.js
  packages/axiom-formatting/src/formatDate.js
  yarn.lock
Labels: :+1: Code Review Passed

#651 feat(Icon): adds new lock icon
  packages/axiom-components/src/Icon/Icon.js
  packages/axiom-materials/src/icon_svgs/lock.svg
  packages/axiom-materials/src/icons.js
Labels: :+1: Design Review Passed, :art: Design Review Needed

#654 fix(babel-plugin-axiom-imports): Member expression literals transform
  packages/babel-plugin-axiom-imports/src/__snapshots__/babel-plugin-axiom-imports.test.js.snap
  packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.js
  packages/babel-plugin-axiom-imports/src/babel-plugin-axiom-imports.test.js
  packages/babel-plugin-axiom-imports/test/property.js
Labels: :+1: Code Review Passed

#655 fix(Badge): Remove incorrect flex end alignment to allow text alignment
  packages/axiom-components/src/Badge/Badge.css
Labels: :+1: Code Review Passed

#656 feat(Reveal): Added option to remove the contents of Reveal when it i…
  packages/axiom-components/src/Reveal/Reveal.js
Labels: :+1: Code Review Passed
