Repository BrandwatchLtd/axiom-react, pull requests merged in 2019-06, with the labels that each got.

#752 feat(TextInput): Adds ability to display form labels inline
  packages/axiom-components/src/DurationPicker/__snapshots__/DurationPicker.test.js.snap
  packages/axiom-components/src/Form/InputWrapper.css
  packages/axiom-components/src/Form/InputWrapper.js
  packages/axiom-components/src/Form/TextInput.js
  site/components/Documentation/Resources/Components/Form.js
Labels: :+1: Design Review Passed, :art: Design Review Needed

#755 feat(Dialog): Add classname prop to Dialog components
  packages/axiom-components/src/Dialog/Dialog.js
  packages/axiom-components/src/Dialog/DialogBody.js
  packages/axiom-components/src/Dialog/DialogFooter.js
  packages/axiom-components/src/Dialog/DialogHeader.js
Labels: :+1: Code Review Passed

#753 fix(DatePicker): pass on initialDate prop
  packages/axiom-components/src/DatePicker/DatePicker.js
  packages/axiom-components/src/DatePicker/DatePickerContext.js
  packages/axiom-components/src/DatePicker/DatePickerSelection.js
Labels: :+1: Code Review Passed

#757 feat(DatePicker): Exporting DatePickerSelection
  packages/axiom-components/src/DatePicker/DatePicker.js
  packages/axiom-components/src/DatePicker/DatePickerSelection.js
  packages/axiom-components/src/index.js
  site/components/Documentation/Resources/Components/DatePicker.js
Labels: :woman_technologist: 1st Code Review Needed, :woman_technologist: 2nd Code Review Needed

#758 fix(InputWrapper): Apply margin to hint when label is inline
  packages/axiom-components/src/Form/InputWrapper.css
  packages/axiom-components/src/Form/InputWrapper.js
  site/components/Documentation/Resources/Components/Form.js
Labels: :+1: Design Review Passed, :woman_technologist: 2nd Code Review Needed

#756 fix(Position): Fixes the margin depending on where the arrow is shown
  packages/axiom-components/src/Position/Position.css
Labels: :+1: Design Review Passed
