Repository BrandwatchLtd/axiom-react, pull requests merged in 2019-10, with the labels that each got.

#798 feat(Dialog): Adds new large and fullscreen options.
  packages/axiom-components/src/Dialog/Dialog.css
  packages/axiom-components/src/Dialog/Dialog.js
  packages/axiom-components/src/Modal/Modal.js
  site/components/Documentation/Resources/Components/Dialog.js
Labels: :broken_heart: Breaking Change

#801 feat(TextInput): Adding a "labelSpace" property
  packages/axiom-components/src/Form/InputWrapper.js
  packages/axiom-components/src/Form/TextInput.js
Labels: :+1: Code Review Passed

#803 feat(Separator): allow className prop
  packages/axiom-components/src/Separator/Separator.js
  packages/axiom-components/src/Separator/Separator.test.js
  packages/axiom-components/src/Separator/__snapshots__/Separator.test.js.snap
Labels: :woman_technologist: 2nd Code Review Needed

#809 feat(Validation): Add "showArrow" property to InlineValidation component
  packages/axiom-components/src/Validation/InlineValidation.js
Labels: :+1: Code Review Passed

#811 feat(Icon): adding filter-line icon
  packages/axiom-components/src/Icon/Icon.js
  packages/axiom-materials/src/icon_svgs/filter-line.svg
  packages/axiom-materials/src/icons.js
Labels: :+1: Code Review Passed

#813 fix(Icon): Runs instagram.svg and filter-line.svg through imageoptim
  packages/axiom-materials/src/icon_svgs/filter-line.svg
  packages/axiom-materials/src/icon_svgs/instagram.svg
Labels: :+1: Code Review Passed
