Repository BrandwatchLtd/axiom-react, pull requests merged in 2019-08, with the labels that each got.

#783 feat(Icon): Adding settings icon
  packages/axiom-components/src/Icon/Icon.js
  packages/axiom-materials/src/icon_svgs/settings.svg
  packages/axiom-materials/src/icons.js
Labels: :+1: Design Review Passed, :woman_technologist: 1st Code Review Needed

#784 Flag color fix
  scripts/process_flags/lib/palette.js
Labels: :+1: Design Review Passed, :woman_technologist: 1st Code Review Needed

#782 fix(DatePickerContext): the date range label shows the correct start date
  packages/axiom-components/src/DatePicker/DatePickerContext.js
Labels: :woman_technologist: 2nd Code Review Needed

#785 fix(animicon): Changed Cross animation
  packages/axiom-components/src/Icon/Animicon.css
  packages/axiom-materials/src/icon_svgs/cross.svg
Labels: :+1: Code Review Passed

#788 chore: rename unsafe lifecycles
  packages/axiom-components/src/AlertDropdown/AlertDropdownSource.js
  packages/axiom-components/src/Avatar/Candytar.js
  packages/axiom-components/src/Dropdown/DropdownContext.js
  packages/axiom-components/src/Editable/EditableLine.js
  packages/axiom-components/src/Image/ImageFallback.js
  packages/axiom-components/src/Portal/Portal.js
  packages/axiom-components/src/Progress/ProgressFinite.js
  packages/axiom-components/src/Progress/ProgressInfinite.js
  packages/axiom-components/src/Reveal/Reveal.js
  packages/axiom-components/src/Tabset/Tabset.js
  packages/axiom-components/src/Transition/Transition.js
  packages/axiom-components/src/Validation/Validate.js
  packages/axiom-documentation-viewer/src/DocumentationApi.js
Labels: :woman_technologist: 2nd Code Review Needed
