Repository BrandwatchLtd/axiom-react, pull requests merged in 2019-09, with the labels that each got.

#789 feat(Dropdown/Select): Changed selected color to grey
  packages/axiom-components/src/Context/Context.css
Labels: :woman_technologist: 1st Code Review Needed

#792 feat(Icon): add drag handle icon
  packages/axiom-components/src/Icon/Icon.js
  packages/axiom-materials/src/icon_svgs/drag.svg
  packages/axiom-materials/src/icons.js
Labels: :+1: Design Review Passed, :woman_technologist: 2nd Code Review Needed

#793 feat(ProgressButton): added flex to content wrapper
  packages/axiom-components/src/Progress/ProgressButton.css
Labels: :woman_technologist: 2nd Code Review Needed

#795 feat(TextInput): Removed condition preventing "clear" icon AND input icon
  packages/axiom-components/src/Form/TextInput.js
  packages/axiom-components/src/Form/TextInput.test.js
  packages/axiom-components/src/Form/__snapshots__/TextInput.test.js.snap
Labels: :+1: Code Review Passed, :broken_heart: Breaking Change
